# Default values for deploy-code chart
image:
  repository: ""
  tag: ""
  pullPolicy: Always

config:
  prefectApiUrl: http://prefect-server.prefect.svc.cluster.local:4200/api

# Environment variables to pass to the container
env:
  # Secrets and sensitive data (set these via --set or values file)
  
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

job:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 1800  # 30 minutes
  ttlSecondsAfterFinished: 300  # 5 minutes
  backoffLimit: 3
